# patch_nfs_details.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 192.168.0.103
            - name: NFS_PATH 
              value: /nfs/kubernetes
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.0.103
            path: /nfs/kubernetes 
            mountOptions:
              - nfsvers=4.2
