apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt  
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: rohitthadani@duck.com # replace for your valid email
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - selector: {}
      http01:
        ingress:
          class: traefik-cert-manager
