apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: traefik-mesh
  includeCRDs: true
  version: 4.1.1
  repo: https://traefik.github.io/charts 
  namespace: kube-system
  valuesInline:
    persistence:
      existingClaim: false
      enabled: true
      accessMode: ReadWrite
      size: 10Gi
      storageClass: nfs-client
      volumeName: traefik-mesh
    tracing:
      deploy: true
      jaeger:
        samplingServerURL: http://jaeger-agent.default.svc:5778/sampling
        localAgentHostPort: jaeger-agent.default.svc:6831
    metrics:
      deploy: true

