apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: traefik-mesh
  includeCRDs: true
  version: 4.1.1
  repo: https://traefik.github.io/charts 
  namespace: kube-system
  valuesInline:
    tracing:
      deploy: false
    metrics:
      deploy: false

