apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: traefik-mesh
  includeCRDs: false
  version: 4.1.1
  repo: https://traefik.github.io/charts 
  namespace: kube-system

