apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: excalidraw-ingress
  namespace: apps
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: Host(`excalidraw.rthadani.xyz`) || Host(`excalidraw.io.local`)
    services:
    - name: excalidraw-service
      passHostHeader: false
      port: 80
      kind: Service
    middlewares:
    - name: strip-prefix
      namespace: apps 
  tls:
    secretName: excalidraw.rthadani.xyz-secret
    #certResolver: default
  
