apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excalidraw-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: PathPrefix('/excalidraw')
    services:
    - name: excalidraw
      passHostHeader: false
      port: 80
  tls:
    certResolver: default
      
  
