apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: excalidraw-ingress
  namespace: apps
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: PathPrefix('/excalidraw')
    services:
    - name: excalidraw
      passHostHeader: false
      port: 80
  tls:
    certResolver: default
      
  
