apiVersion: traefik.containo.us/v1alpha1 
kind: TraefikService
metadata:
  name: excalidraw 
spec:
  selector:
    app.kubernetes.io/name: excalidraw
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
      name: http

