apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
- name: cnpg 
  includeCRDs: true
  repo: https://cloudnative-pg.github.io/charts 
  namespace: cnpg  
  releaseName: cnpg 
  valuesInline:
    replicaCount: 1
    rbac:
      create: false

