apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

helmCharts:
  - name: postgresql
    releaseName: postgres
    repo: https://charts.bitnami.com/bitnami
    version: 12.1.10
    valuesFile: values.yaml
