apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

# resources:
#   - service.yaml
#   - ingress.yaml

helmCharts:
  - name: postgresql
    releaseName: postgres
    repo: https://charts.bitnami.com/bitnami
    valuesInline: 
       image:
          registry: ghcr.io
          repository: ankane/pgvector
          tag: "postgres15-vec0.5.0"
          pullPolicy: IfNotPresent
       auth:
         postgresqlUsername: pg_user
         postgresqlPassword: pg_password
         postgresqlDatabase: toro 
       primary:
         persistence:
           enabled: true
           storageClass: nfs-client
       replicaCount: 1

        # Use initdbScripts to create the pgvector extension automatically
       initdbScripts:
         01-create-extension.sql: |
             CREATE EXTENSION IF NOT EXISTS vector;
