apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apps

# resources:
#   - service.yaml
#   - ingress.yaml

helmCharts:
  - name: postgresql
    releaseName: postgres
    repo: https://charts.bitnami.com/bitnami
    valueFiles: 
      - values.yaml
