image:
  registry: ghcr.io
  repository: ankane/pgvector
  tag: "15"
  namespace: apps
  pullPolicy: IfNotPresent

postgresqlUsername: pg_user
postgresqlPassword: pg_password
postgresqlDatabase: toro 

primary:
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
    storageClass: nfs-client
replicaCount: 1

# Use initdbScripts to create the pgvector extension automatically
initdbScripts:
  01-create-extension.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
