image:
  registry: ghcr.io
  repository: ankane/pgvector
  tag: "postgres15-vec0.5.0"
  pullPolicy: IfNotPresent
auth:
  postgresqlUsername: pg_user
  postgresqlPassword: pg_password
  postgresqlDatabase: toro 
primary:
  persistence:
    enabled: true
    storageClass: nfs-client
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
replicaCount: 1

# Use initdbScripts to create the pgvector extension automatically
initdbScripts:
  01-create-extension.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
