kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: docker-registry
  namespace: apps 

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`io.local`)
      kind: Rule
      services:
        - name: release-name-docker-registry
          port: 5000
