apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cert-manager
  includeCRDs: true
  version: v1.14.5
  repo: https://charts.jetstack.io 
  namespace: cert-manager  

patches:
  - path: ./remove-instance-label.jsonpatch.yaml
    target:
      kind: CustomResourceDefinition
      labelSelector: app.kubernetes.io/instance=cert-manager
