apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: jetstack/cert-manager
  installCRDs: true
  version: v1.14.5
  repo: https://charts.jetstack.io 
  namespace: cert-manager  
