apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cert-manager
  version: v1.14.5
  repo: https://charts.jetstack.io 
  namespace: cert-manager  
  valuesInline:
    installCRDs: true
